export const PH_PROVINCES = [
  'Metro Manila',
  'Cebu',
  'Davao del Sur',
  'Pampanga',
  'Laguna',
  'Batangas',
  'Iloilo',
  'Negros Occidental',
  'Misamis Oriental',
  'Bulacan',
  'Cavite',
  'Rizal',
  'Quezon',
  'Nueva Ecija',
  'Tarlac',
  'Zambales',
  'Bohol',
  'Leyte',
  'Zamboanga del Sur',
  'Bukidnon',
] as const

export const COUNTRIES = [
  'Philippines',
  'Saudi Arabia',
  'United Arab Emirates',
  'Qatar',
  'Kuwait',
  'Bahrain',
  'United States',
  'Canada',
  'United Kingdom',
  'Australia',
  'Singapore',
  'Japan',
  'South Korea',
  'Hong Kong',
  'Italy',
  'Other',
] as const
